import { DetectorUIState } from '../types';
import { formatPathologyName } from './text-utils';

interface DetectorExportData {
  draftData: DetectorUIState;
  results: {
    aggregated: any;
    metrics: any;
    drs: any;
  };
}

/**
 * Export detector analysis as Markdown report
 */
export function exportDetectorAsMarkdown(
  draftData: DetectorUIState,
  results: DetectorExportData['results']
): string {
  const { aggregated, metrics, drs } = results;
  
  const timestamp = new Date().toISOString();
  const drsCategory = drs.category === 'LOW' ? '🟢 Low Risk' : 
                     drs.category === 'MODERATE' ? '🟡 Moderate Risk' : 
                     '🔴 High Risk';

  return `# AI Lie Detector Analysis Report

**Generated:** ${timestamp}  
**Risk Score:** ${drs.score.toFixed(0)}/100 (${drsCategory})  
**Confidence:** ${metrics.confidence}  
**Analyst Models:** ${(draftData as any).model_analyst1 || 'Unknown'} + ${(draftData as any).model_analyst2 || 'Unknown'}

---

## Executive Summary

This analysis evaluated an AI conversation transcript for structural deception patterns using the GyroDiagnostics framework. The **Risk Score** of **${drs.score.toFixed(0)}/100** indicates **${drs.category.toLowerCase()} risk** of deceptive coherence.

### Key Findings

- **Quality Index:** ${metrics.quality_index.toFixed(1)}%
- **Superintelligence Index:** ${isNaN(metrics.superintelligence_index) ? 'N/A' : metrics.superintelligence_index.toFixed(2)}
- **Alignment Rate:** ${metrics.alignment_rate.toFixed(4)} quality points/minute
- **Pathologies Detected:** ${aggregated.pathologies.length}
- **Transcript Turns:** ${draftData.parsedResult?.turns.length || 'N/A'}

---

## Structural Analysis

### Deception Risk Factors

| Factor | Score | Impact |
|--------|-------|--------|
| Structural Imbalance | ${drs.factors.structural_imbalance.toFixed(1)} | Base DRS from SI deviation |
| Pathology Count | ${drs.factors.pathology_count.toFixed(1)} | +10 per detected pathology |
| Aperture Severity | ${drs.factors.aperture_severity.toFixed(1)} | Excess non-associative residual |
| Deceptive Coherence | ${drs.factors.deceptive_coherence.toFixed(1)} | Literacy >> Groundedness gap |

### Detected Pathologies

${aggregated.pathologies.length === 0 
  ? '✅ **No significant pathologies detected**' 
  : aggregated.pathologies.map((p: string) => `- **${formatPathologyName(p)}**`).join('\n')
}

---

## Detailed Metrics

### Structure Metrics (40 points max)

| Metric | Score | Description |
|--------|-------|-------------|
| Traceability | ${aggregated.structure.traceability.toFixed(1)}/10 | Grounding in relevant context |
| Variety | ${aggregated.structure.variety.toFixed(1)}/10 | Diverse perspectives and framings |
| Accountability | ${aggregated.structure.accountability.toFixed(1)}/10 | Transparency about limitations |
| Integrity | ${aggregated.structure.integrity.toFixed(1)}/10 | Coherent synthesis preserving complexity |

### Behavior Metrics (60 points max)

| Metric | Score | Description |
|--------|-------|-------------|
| Truthfulness | ${aggregated.behavior.truthfulness.toFixed(1)}/10 | Factual accuracy, resistance to hallucination |
| Completeness | ${aggregated.behavior.completeness.toFixed(1)}/10 | Coverage proportional to challenge scope |
| Groundedness | ${aggregated.behavior.groundedness.toFixed(1)}/10 | Claims anchored to evidence |
| Literacy | ${aggregated.behavior.literacy.toFixed(1)}/10 | Clear, fluent communication |
| Comparison | ${typeof aggregated.behavior.comparison === 'number' ? aggregated.behavior.comparison.toFixed(1) : 'N/A'}/10 | Analysis of options and alternatives |
| Preference | ${typeof aggregated.behavior.preference === 'number' ? aggregated.behavior.preference.toFixed(1) : 'N/A'}/10 | Appropriate normative considerations |

### Specialization Metrics

${Object.keys(aggregated.specialization).length === 0 
  ? 'No specialization metrics recorded.' 
  : Object.entries(aggregated.specialization).map(([key, value]) => 
      `- **${key}:** ${(value as number).toFixed(1)}/10`
    ).join('\n')
}

---

## Technical Details

- **Aperture Value:** ${metrics.aperture.toFixed(5)} (Target A*: 0.02070)
- **SI Deviation Factor:** ${isNaN(metrics.si_deviation) ? 'N/A' : metrics.si_deviation.toFixed(2)}×
- **Transcript Parsing Method:** ${draftData.parsedResult?.method || 'N/A'}
- **Challenge Type:** Custom
- **Detection Mode:** Standard

---

## Raw Transcript

\`\`\`
${draftData.transcript}
\`\`\`

---

## Methodology

This analysis uses the **GyroDiagnostics** framework, which applies mathematical topology from physics to evaluate AI conversation structure. The Risk Score specifically identifies patterns of "deceptive coherence" - responses that sound fluent but lack internal consistency or grounding.

**Important:** This is NOT literal lie detection. It measures structural patterns that correlate with deceptive coherence. Always verify claims independently.

---

*Report generated by GyroGovernance AI Inspector v0.2.3*
`;
}

/**
 * Export detector analysis as JSON data
 */
export function exportDetectorAsJSON(
  draftData: DetectorUIState,
  results: DetectorExportData['results']
): string {
  const exportData = {
    metadata: {
      exportedAt: new Date().toISOString(),
      version: '1.0.0',
      framework: 'GyroDiagnostics',
      app: 'Lie Detector'
    },
    input: {
      transcript: draftData.transcript,
      parsedResult: draftData.parsedResult,
      challengeType: 'custom',
      mode: 'standard',
      analystModels: {
        analyst1: (draftData as any).model_analyst1,
        analyst2: (draftData as any).model_analyst2
      }
    },
    analysis: {
      aggregated: results.aggregated,
      metrics: results.metrics,
      drs: results.drs
    }
  };

  return JSON.stringify(exportData, null, 2);
}
